// Context
import { useContext } from 'react'
import CoursesContext from '../context/Courses/CoursesContext'

const useCourses = (props) => {
  const {
    handleCreate,
    handleDelete,
    getLesson,
    getLinkLesson,
    getTitleLesson,
    setTitleLesson,
    setLinkLesson,
    setLessons,
    handleSubmit,
    files,
    setFiles,
    uploadModal,
    setUploadModal,
    courseImage,
    setCourseImage,
    coursePoster,
    setCoursePoster,
    color,
    setColor,
    isPin,
    setIsPin,
    isFree,
    setIsFree,
    description,
    setDescription,
    price,
    setPrice,
    excerpt,
    setExcerpt,
    name,
    setName,
    colors,
    getContentLesson,
    setContentLesson,
    selectLessenFile,
    handleEdit,
  } = useContext(CoursesContext)

  return {
    handleCreate,
    handleDelete,
    getLesson,
    getLinkLesson,
    getTitleLesson,
    setTitleLesson,
    setLinkLesson,
    setLessons,
    handleSubmit,
    files,
    setFiles,
    uploadModal,
    setUploadModal,
    courseImage,
    setCourseImage,
    coursePoster,
    setCoursePoster,
    color,
    setColor,
    isPin,
    setIsPin,
    isFree,
    setIsFree,
    description,
    setDescription,
    price,
    setPrice,
    excerpt,
    setExcerpt,
    name,
    setName,
    colors,
    selectLessenFile,
    getContentLesson,
    setContentLesson,
    handleEdit,
  }
}

export default useCourses
